/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        CommandInterpreter nimCommandInterpreter = new NimCommandsInterpreter(new SessionManager(NimSession.class));

        CommandReader commandReader = new SocketCommandReader(nimCommandInterpreter);
        commandReader.start();
    }
}
